--Creation Data Base-- >
CREATE DATABASE Gestion_Packages
SHOW DATABASES
USE Gestion_Packages

--Creation des Tables -->
CREATE TABLE Auteurs (
    AuteurId INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE packages (
    PackageId INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE versions (
    versionId INT AUTO_INCREMENT PRIMARY KEY,
    packageId INT NOT NULL,
    version_number VARCHAR(20) NOT NULL,
    creation_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (packageId) REFERENCES packages(packageId)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE package_auteur (
    id INT AUTO_INCREMENT PRIMARY KEY,
    auteurId INT NOT NULL,
    packageId INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (auteurId) REFERENCES Auteurs(AuteurId)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (packageId) REFERENCES packages(packageId)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


